"""'initial'

Revision ID: 871948c65777
Revises: 
Create Date: 2024-07-30 12:16:45.933307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '871948c65777'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('movie_code', sa.Integer(), nullable=True),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('date_added', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('movie_code')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
                    sa.Column('date_added', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('movies')
    # ### end Alembic commands ###
